### ISSUE TITLE
Resolve display issue of magazine buttons

### ISSUE THREAD

**Issue by solocommand** [parameter1/ac-business-media-websites#84]
Ref [BCMS-441](https://southcomm.atlassian.net/browse/BCMS-441)

Client requests that buttons be displayed on a single line, rather than breaking to a new line. Investigate layout options to resolve that request.

![image](https://user-images.githubusercontent.com/1778222/75580145-dbbed900-5a2c-11ea-9574-82bf2219baf5.png)

**Comment by zarathustra323** [comment]
@solocommand This is being caused by the `max-width: 70%` on the `.node__footer-left` class. Unfortunately, this class needs to stay (generically) for all "regular" footer nodes. I modifier could be added to this specific node to address the width, or a modifier could be added to all content cards to handle the 70%
